### ISSUE TITLE
rgcookbook fails to compile locally

### ISSUE THREAD

**Issue by BB1464** [wch/rgcookbook#10]
Hi Dear @wch I cloned the repository of the rgcookbook and I tried to compile the book and I get the following error below. Please can you advice me on how to resolve this? Thank you and best regards.

Error in render_book_script(output_format, envir, quiet) : 
  Error 127 attempting to render book
Calls: <Anonymous> -> <Anonymous> -> in_dir -> render_book_script
In addition: Warning message:
In system2("make") : '"make"' not found
Execution halted

Exited with status 1.

**Comment by wch** [comment]
Hi, you'll need to install `make` on your computer. This is a build tool that's used for many different software projects. How you install it vary depending on what platform you're using. I can't provide instructions, but I'm sure that there are many guides out there about how to do it.

**Comment by BB1464** [comment]
@wch thank you for your reply, I am using windows operating system, I am going to check online instructions on how to install make for my system.
